[package]
name = "rita"
version = "0.1.14"
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"

[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[features]
default = []
system_alloc = []
development = []


[dependencies]
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types", features = ["actix"]}
babel_monitor = { path = "../babel_monitor" }
clu = { path = "../clu" }
exit_db = { path = "../exit_db" }
num256 = "0.1"
settings = { path = "../settings" }

syslog = "^4.0"
actix = "0.7.4"
actix-web = { version = "0.7.4", default_features = false }
actix_derive = "0.3.0"
bytes = "0.4.10"
config = "0.9.0"
diesel = { version = "1.3.3", features = ["sqlite"] }
libsqlite3-sys = { version = "0.9.3", features = ["bundled"] }
docopt = "0.8.3"
dotenv = "0.13.0"
env_logger = "0.5.13"
eui48 = {git="https://github.com/althea-mesh/eui48.git"}
failure = "0.1.2"
futures = "0.1.24"
ipnetwork = "0.13.1"
lazy_static = "1.1.0"
lettre = {git="https://github.com/lettre/lettre.git"}
lettre_email = {git="https://github.com/lettre/lettre.git"}
log = "0.4.5"
minihttpse = "0.1.6"
mockito = "0.13.0"
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
rand = "0.5.5"
reqwest = "0.9.2"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.28"
tokio = "0.1.8"
tokio-io = "0.1.8"
tokio-codec = "0.1.0"
regex = "1.0.5"
trust-dns-resolver = "0.9.1"
handlebars = "1.0.3"
byteorder = { version = "1.2.6", features = ["i128"] }
openssl-probe = "0.1.2"
num-traits="0.2"
